### PR TITLE
Add param to MySQL executor

### PR DESCRIPTION
**Pull request by mchompalova**

### CODE REVIEW

**Comment by epavlova** [comment]
> "TEST_RDS_DSN_PREFIX" and "DB_TEST_URL" have the same meaning. So let's fix this. I suggest the following steps:
> 
> 1. In this PR - let's rename "TEST_RDS_DSN_PREFIX" to "TEST_DB_DSN" to be more generic and to reflect the real meaning of its value.
> 2. Fix "concept-events-notifications" to use this new variable
> 3. Fix "generic-rw-aurora" to use this new variable
> 4. Remove "DB_TEST_URL" from the orb.


If we know for sure that both environment variables have the same meaning, why we should add the new one. Couldn't we just use `DB_TEST_URL` in the `concepts-events-notifications` so we don't have to touch the orb or `generic-rw-aurora`? `DB_TEST_URL` is general enough.

**Comment by mchompalova** [comment]
`generic-rw-aurora` builds successfully with this version.

**Comment by mchompalova** [comment]
> What is the reason not to use the current parameter `db-test-url`?

I thought we need 2 params because of `generic-rw-aurora`. Actually, the build passes with the default value, which is "root:password@/". I updated the orb.

**Comment by epavlova** [comment]
> > What is the reason not to use the current parameter `db-test-url`?
> 
> I thought we need 2 params because of `generic-rw-aurora`. Actually, the `generic-rw-aurora` build passes with the default value, which is "root:password@/". I updated the orb.

Great, than do we need to keep `mysql-database` parameter with default value `pac`? Otherwise I'm okay with approving the PR.

**Comment by karsov** [comment]
> If we know for sure that both environment variables have the same meaning, why we should add the new one. Couldn't we just use DB_TEST_URL in the concepts-events-notifications so we don't have to touch the orb or generic-rw-aurora? DB_TEST_URL is general enough.

I wrote this thinking that we are not going to fix all services now.

> What is the reason not to use the current parameter `db-test-url`?

The variable name is misleading. It is not a URL, it is a [DSN](https://github.com/go-sql-driver/mysql#dsn-data-source-name). But it may be easier to reuse the variable.
@epavlova

**Comment by epavlova** [comment]
I don't think that fixing the variable name is significant enough for releasing major version of the orb.

**Pull request merged**
